services:
  - type: web
    name: popping
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: popping-data
      mountPath: /opt/render/project/src
      sizeGB: 1
